### ISSUE TITLE
Getting error while run test on namespace

### ISSUE THREAD

**Issue by nivGandhi** [datreeio/kubectl-datree#2]
Hello Team,

I am getting below error while run test on namespace.

E0722 14:54:43.548729   17348 run.go:120] "command failed" err="unknown command \"datree\" for \"kubectl\""

Note: I have install on WSL environment.

**Comment by adifayer** [comment]
According to the error, seems like something went wrong during the installation of the plugin. 
Do you see Datree's plugin when executing the following command: `kubectl plugin list`?

**Comment by nivGandhi** [comment]
Sorry, It was my mistake during the installation. it is working now.
